export const ADD_PARENT_TODO = "ADD_TODO";
export const ADD_CHILD_TODO = "ADD_CHILD_TODO";
export const REMOVE_PARENT_TODO = "REMOVE_PARENT_TODO";
export const REMOVE_CHILD_TODO = "REMOVE_CHILD_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const CHANGE_SELECTED_TODO = "CHANGE_SELECTED_TODO";
export const DRAG_TODO = "DRAG_TODO";
